database:
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    properties:
        charset: UTF-8
    url: jdbc:mysql://localhost/clubu

solrUrl: http://localhost:8983/solr/clubu

